# CI/CD

image: archlinux
packages:
  - rustup
sources:
  - https://git.sr.ht/~hadronized/kak-tree-sitter
tasks:
  - setup: |
      rustup set profile minimal
      rustup default stable
      rustup component add rustfmt
  - check: |
      pwd
      cd kak-tree-sitter
      cargo fmt -q
  - build: |
      pwd
      cd kak-tree-sitter
      cargo build
  - test: |
      pwd
      cd kak-tree-sitter
      cargo test
